In [52]:
import numpy as np

In [53]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [74]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array generation


In [55]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np.zeros(8) 

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
np.zeros((6,6)) #row and column

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [58]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [59]:
np.linspace(1,6,10)      #returns evenly space numbers # in between 1 and 6 it will have 10 spaces


array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

Random numbers generation

In [60]:
np.random.randn(10)

array([ 0.57788927, -1.26342251,  0.99314535,  1.02994156, -1.52768314,
        0.09947966, -1.70861574,  0.42277961,  1.55654105,  1.1012455 ])

In [61]:
np.random.randint(10,20,) #it will generate only one number between 10 to 20

12

In [62]:
np.random.randint(10,20,20)

array([18, 19, 16, 15, 10, 14, 19, 13, 14, 18, 18, 11, 18, 12, 19, 10, 19,
       17, 17, 17], dtype=int32)

Array attributes

In [63]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a.shape #used to provide the number of rows and coloumn

(3, 3)

array methods

In [65]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a.min()

np.int64(1)

In [67]:
a.max()

np.int64(9)

In [68]:
a.sum()

np.int64(45)

In [69]:
np.sum(a,axis=0) #if you want to sum the coloumn part then you have to put axis =0 and axis = 1 for row summation

array([12, 15, 18])

In [70]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [71]:
a.mean()

np.float64(5.0)

In [72]:
a.std()

np.float64(2.581988897471611)

Reshape and resize

In [76]:
a=np.arange(1,31)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
a.reshape(6,5) #it will reshape ur array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])