In [10]:
import numpy as np

In [11]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array generation


In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.zeros(8) 

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((6,6)) #row and column

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(1,6,10)      #returns evenly space numbers # in between 1 and 6 it will have 10 spaces


array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

Random numbers generation

In [18]:
np.random.randn(10)

array([ 0.78487402,  1.60976419, -1.8438879 , -0.32278456, -0.25303965,
       -0.11740433,  0.84066489, -1.09119694, -0.98089834, -0.03673686])

In [19]:
np.random.randint(10,20,) #it will generate only one number between 10 to 20

19

In [20]:
np.random.randint(10,20,20)

array([14, 11, 17, 13, 19, 10, 13, 13, 18, 16, 16, 10, 14, 15, 19, 13, 19,
       18, 15, 16], dtype=int32)

Array attributes

In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.shape #used to provide the number of rows and coloumn

(3, 3)

array methods

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a.min()

np.int64(1)

In [29]:
a.max()

np.int64(9)

In [30]:
a.sum()

np.int64(45)

In [ ]:
np.sum(a,axis=0) #if you want to sum the coloumn part then you have to put axis =0 and axis = 1 for row summation

array([12, 15, 18])

In [33]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [ ]:
a.mean()

np.float64(5.0)