In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [2]:
a=np.arange(10,26)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [3]:
a[9]

np.int64(19)

In [ ]:
a[1:10] #startpoint:endpoint+1 

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a[2::2]#it will take the step of 2

array([12, 14, 16, 18, 20, 22, 24])

NUMPY INDEXING AND SLICING OF MATRIX

In [7]:
a=np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])