ARITHMETIC OPERATIONS

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
sum=a+b
sum

array([ 7,  9, 11, 13, 15])

In [3]:
sub=a-b 
sub

array([-5, -5, -5, -5, -5])

In [4]:
a*b

array([ 6, 14, 24, 36, 50])

In [5]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [6]:
a//b #floor value

array([0, 0, 0, 0, 0])

In [7]:
a**b #power

array([      1,     128,    6561,  262144, 9765625])

BROADCASTING

In [8]:
l=[10,20,30,40]
arr=np.array(l)

In [9]:
arr+10

array([20, 30, 40, 50])

In [10]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])