ARITHMETIC OPERATIONS

In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
sum=a+b
sum

array([ 7,  9, 11, 13, 15])

In [6]:
sub=a-b 
sub

array([-5, -5, -5, -5, -5])

In [7]:
a*b

array([ 6, 14, 24, 36, 50])

In [8]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a//b #floor value

array([0, 0, 0, 0, 0])

In [ ]:
a**b #power

array([      1,     128,    6561,  262144, 9765625])